better error handling in workflows

diff --git a/.github/workflows/build_img_ca.yml b/.github/workflows/build_img_ca.yml
--- a/.github/workflows/build_img_ca.yml
+++ b/.github/workflows/build_img_ca.yml
@@ -100,10 +100,15 @@ jobs:
         shell: bash
         run: |
           echo "release_id: ${{ steps.get-release-id.outputs.release_id }}"
+          if [[ $release_id == "null" ]]; then
+            echo "Failed to create release. Response: $release"
+            exit 1
+          fi
 
   # Stage 4: Upload to Release
   upload-image:
     runs-on: ubuntu-latest
+    if: ${{ needs.check-release-or-create.outputs.release_id }}
     needs: [modify-rpi-image, check-release-or-create, get-date-release-name]
     steps:
       - name: Restore Cache for Image
diff --git a/.github/workflows/build_img_gui.yml b/.github/workflows/build_img_gui.yml
--- a/.github/workflows/build_img_gui.yml
+++ b/.github/workflows/build_img_gui.yml
@@ -90,7 +90,7 @@ jobs:
           if [[ "$release_id" == "null" ]]; then
             release=$(curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
-              -d "{\"tag_name\":\"$release_name\",\"name\":\"$release_name\",\"body\":\RaspOVOS + ovos-shell via EGLFS\"}" \
+              -d "{\"tag_name\":\"$release_name\",\"name\":\"$release_name\",\"body\":\RaspOVOS and ovos-shell via EGLFS\"}" \
               "https://api.github.com/repos/${{ github.repository }}/releases")
             release_id=$(echo $release | jq -r .id)
           fi
@@ -100,11 +100,16 @@ jobs:
         shell: bash
         run: |
           echo "release_id: ${{ steps.get-release-id.outputs.release_id }}"
+          if [[ $release_id == "null" ]]; then
+            echo "Failed to create release. Response: $release"
+            exit 1
+          fi
 
   # Stage 4: Upload to Release
   upload-image:
     runs-on: ubuntu-latest
     needs: [modify-rpi-image, check-release-or-create, get-date-release-name]
+    if: ${{ needs.check-release-or-create.outputs.release_id }}
     steps:
       - name: Restore Cache for Image
         uses: actions/cache@v4
